# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
from algorithms.tree import pretty_print as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "\n    An avl tree.\n    "
    module_0.tree_print(str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bytes_0 = b""
    var_0 = module_0.tree_print(bytes_0)
    list_0 = [var_0, var_0]
    module_0.tree_print(list_0)


def test_case_2():
    bool_0 = True
    tuple_0 = (bool_0,)
    dict_0 = {tuple_0: bool_0, tuple_0: tuple_0, bool_0: tuple_0}
    var_0 = module_0.tree_print(dict_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bool_0 = True
    str_0 = "\n        Left rotation\n        "
    tuple_0 = (str_0,)
    tuple_1 = (bool_0, tuple_0)
    module_0.tree_print(tuple_1)
