# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
from algorithms.tree import invert_tree as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    var_0 = module_0.reverse(none_type_0)
    str_0 = "\n    An avl tree.\n    "
    module_0.reverse(str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = True
    module_0.reverse(bool_0)
