# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
from algorithms.tree import is_subtree as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = True
    module_0.is_subtree(bool_0, bool_0)


def test_case_1():
    none_type_0 = None
    var_0 = module_0.comp(none_type_0, none_type_0)
    assert var_0 is True


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = True
    none_type_0 = None
    var_0 = module_0.comp(bool_0, none_type_0)
    assert var_0 is False
    module_0.comp(bool_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bool_0 = True
    none_type_0 = None
    var_0 = module_0.comp(bool_0, none_type_0)
    assert var_0 is False
    var_1 = module_0.comp(none_type_0, bool_0)
    assert var_1 is False
    module_0.comp(bool_0, bool_0)
