# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
from algorithms.tree import is_balanced as module_0


def test_case_0():
    none_type_0 = None
    var_0 = module_0.is_balanced(none_type_0)
    assert var_0 is True
    var_1 = module_0.is_balanced(none_type_0)
    assert var_1 is True


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = False
    module_0.is_balanced(bool_0)
