# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
from algorithms.tree import same_tree as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    var_0 = module_0.is_same_tree(none_type_0, none_type_0)
    assert var_0 is True
    var_1 = module_0.is_same_tree(var_0, none_type_0)
    assert var_1 is False
    module_0.is_same_tree(var_1, var_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = True
    module_0.is_same_tree(bool_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    var_0 = module_0.is_same_tree(none_type_0, none_type_0)
    assert var_0 is True
    var_1 = module_0.is_same_tree(var_0, none_type_0)
    assert var_1 is False
    var_2 = module_0.is_same_tree(none_type_0, var_1)
    assert var_2 is False
    module_0.is_same_tree(var_0, var_2)
