# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
from algorithms.tree import min_height as module_0
from algorithms.tree import tree as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"\xaa\xce\xd1*"
    module_0.min_depth(bytes_0)


def test_case_1():
    none_type_0 = None
    var_0 = module_0.min_height(none_type_0)
    assert var_0 == 0


@pytest.mark.xfail(strict=True)
def test_case_2():
    bytes_0 = b"'\x84\x9c\xf7\x88.\x19\xe4\xa1T\x8f"
    module_0.min_height(bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bool_0 = False
    module_0.print_tree(bool_0)


def test_case_4():
    tree_node_0 = module_1.TreeNode()
    var_0 = module_0.print_tree(tree_node_0)


def test_case_5():
    tree_node_0 = module_1.TreeNode()
    var_0 = module_0.min_height(tree_node_0)
    assert var_0 == 1
